name: Autobump dependencies

on: 
  push:
    branches:
      - feat/autobump

permissions:
  contents: write

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Configure github-actions-bot user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions-bot"

      - name: Tap
        run: brew tap moonlight8978/tap

      - name: Install tools
        run: |
          curl -fsSL https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-arm64 -o jq
          chmod +x jq
          sudo mv jq /usr/local/bin/jq

      - name: Bump casks
        run: |
          cat .github/autobump.txt | xargs | while read formulae; do
            brew livecheck "$formulae" --json | jq -r '.[].version.latest' > "$formulae.txt"
            version=$(cat "$formulae.txt")
            brew bump-cask-pr $formulae --write-only --version $version --no-fork --dry-run
          done
